FORMAT: 1A
HOST: https://zoho.syncdatamaster.com/sync/

# ZohoEasySync

ZohoEasySync выполняет синхронизацию данных с ZohoCRM  в локальные базы данных MySQL

## Запуск синхронизации [/run/{account}&{token}&{dbhost}&{dbport}&{dbuser}&{dbpass}&{dbname}&{modules}&{datefrom}&{truncate}]

При отправке запроса синхронизации возможно передать или параметр **datefrom**, или параметр **truncate**. 
Одновременно оба эти параметры указывать не нужно.

+ Parameters
    + account (required, string) - Уникальный идентификатор клиента
    + token (required, string) - Токен ZohoCRM
    + dbhost (required, string) - Хост базы данных
    + dbport (required, integer) - Порт базы данных
    + dbuser (required, string) - Пользователь базы данных
    + dbpass (required, string) - Пароль пользователя базы данных
    + dbname (required, string) - Название базы данных
    + modules (required, string) - Список синхронизируемых модулей
    + datefrom (optional, date) - Синхронизация записей, созданных/изменненных после указанной даты 
    + truncate (optional, string) - Полная очистка таблиц указанных модулей
    
### Отправка запроса [POST]

+ Request (application/json)

    + Headers
    
            Login: testLogin,
            Password: testPassword
            
            
+ Response 200 (application/json)

    + Body

            {
                "processid": 154541
            }

## Проверка статуса процесса [/status/{processid}]

Значение уникального идентификатора процесса **processid** возвращается в ответе на запрос запуска синхронизации.

| Статус     | Код статуса | Описание                       |
|------------|:-----------:|--------------------------------|
| completed  |     204     | Синхронизация выполнена        |
| waiting    |     205     | Задача синхронизации в очереди |
| inprogress |     206     | Синхронизация выполняется      |
| canceled   |     207     | Задача синхронизации отменена  |


+ Parameters
    + processid (required, integer) - Уникальный идентификатор процесса


### Отправка запроса [POST]

+ Request (application/json)

    + Headers

            Login: testLogin,
            Password: testPassword

    + Body

            {
                "processid": 154541
            }

+ Response 200 (application/json)

    + Body

            {
                "processid": 154541,
                "statuscode": 205,
                "status": "waiting"
            }
               
            
## Отмена процесса [/stop/{processid}]

Значение уникального идентификатора процесса **processid** возвращается в ответе на запрос запуска синхронизации.

+ Parameters
    + processid (required, integer) - Уникальный идентификатор процесса


### Отправка запроса [POST]


+ Request (application/json)

    + Headers

            Login: testLogin,
            Password: testPassword

    + Body

            {
                "processid": 154541
            }


+ Response 200 (application/json)

    + Body

            {
                "processid": 154541,
                "statuscode": 207,
                "status": "canceled"
            }