FORMAT: 1A
HOST: https://zoho.syncdatamaster.com/sync/

# ZohoEasySync

ZohoEasySync выполняет синхронизацию данных с ZohoCRM  в локальные базы данных MySQL

## Запуск синхронизации [/run/]



| Параметр | Описание                                                          |     Тип    | Обязательный |
|----------|-------------------------------------------------------------------|:----------:|:------------:|
| account  | Уникальный идентификатор клиента                                  |   String   |      Да      |
| token    | Токен ZohoCRM                                                     |   String   |      Да      |
| dbhost   | Хост базы данных                                                  |   String   |      Да      |
| dbport   | Порт базы данных                                                  |   Integer  |      Да      |
| dbuser   | Пользователь базы данных                                          |   String   |      Да      |
| dbpass   | Пароль пользователя базы данных                                   |   String   |      Да      |
| dbname   | Название базы данных                                              |   String   |      Да      |
| modules  | Список синхронизируемых модулей                                   |   String   |      Да      |
| day_ago  | Синхронизация созданных/измененных записей за посление n дней     |   Integer  |      Нет     |
| truncate | Полная очистка таблиц указанных модулей перед синхронизацией      |   String   |      Нет     |
   
   
При отправке запроса синхронизации возможно передать или параметр **datefrom**, или параметр **truncate**. 
Одновременно оба эти параметры указывать не нужно.



### Отправка запроса [POST]

+ Request (application/json)

    + Headers
    
            Login: testLogin,
            Password: testPassword
            
    + Body

            {
                "account": "3110002454545724579",
                "token": "xmdf7xdsf67sdj7dsf",
                "dbhost": "10.10.10.10",
                "dbport": 3306,
                "dbuser": "someuser",
                "dbpass": "somepassword",
                "dbname": "zohosync",
                "modules": "Products,Contacts,Potentials,Sales_Orders"
                "day_ago": 15
            }

            
            
+ Response 200 (application/json)

    + Body

            {
                "process_id": 0123456789
            }

## Проверка статуса процесса [/status/{process_id}]

Значение уникального идентификатора процесса **process_id** возвращается в ответе на запрос запуска синхронизации.

| Статус     | Описание                       |
|------------|--------------------------------|
| completed  | Синхронизация выполнена        |
| waiting    | Задача синхронизации в очереди |
| inprogress | Синхронизация выполняется      |
| canceled   | Задача синхронизации отменена  |

+ Parameters
    + process_id (required, Integer) - Идентификатор процесса

### Отправка запроса [GET]

+ Request (application/json)

    + Headers

            Login: testLogin,
            Password: testPassword


+ Response 200 (application/json)

    + Body

            {
                "status": "waiting"
            }
               
            
## Отмена процесса [/stop/]

Значение уникального идентификатора процесса **process_id** возвращается в ответе на запрос запуска синхронизации.



### Отправка запроса [POST]


+ Request (application/json)

    + Headers

            Login: testLogin,
            Password: testPassword

    + Body

            {
                "process_id": 0123456789
            }


+ Response 200 (application/json)

    + Body

            {
                "status": "Process was stopped"
            }