FORMAT: 1A
HOST: https://zoho.syncdatamaster.com/sync/

# ZohoEasySync

Ресурс ZohoEasySync выполняет синхронизацию данных с ZohoCRM  в локальные базы данных MySQL

## Запуск синхронизации [/run/{account}&{token}&{dbhost}&{dbport}&{dbuser}&{dbpass}&{dbname}&{modules}&{datefrom}]

+ Parameters
    + account (required, string) - Уникальный идентификатор клиента
    + token (required, string) - Токен ZohoCRM
    + dbhost (required, string) - Хост базы данных
    + dbport (required, string) - Порт базы данных
    + dbuser (required, string) - Пользователь базы данных
    + dbpass (required, string) - Пароль пользователя базы данных
    + dbname (required, string) - Название базы данных
    + modules (required, string) - Список синхронизируемых модулей
    + datefrom (optional, date) - Синхронизация записей, созданных/изменненных после указанной даты 
    
### Отправка запроса [POST]

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 200 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }

## Проверка статуса процесса [/status/{processid}]

+ Parameters
    + processid (required, processid) - Уникальный идентификатор процесса, полученного в отчете при запуске синхронизации


        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

### Отправка запроса [POST]

+ Response 200 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
            
## Отмена процесса [/stop/{processid}]

+ Parameters
    + processid (required, processid) - Уникальный идентификатор процесса, полученного в отчете при запуске синхронизации


### Отправка запроса [POST]


        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 200 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }